"""Add page field to search_history

Revision ID: 1546172e80df
Revises: 9ebe66bd70a4
Create Date: 2024-12-15 14:38:13.652549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1546172e80df'
down_revision = '9ebe66bd70a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.alter_column('page',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.alter_column('page',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
