"""Add search_count to SearchHistory

Revision ID: 1d654562a0fe
Revises: 95adbfbc37ea
Create Date: 2024-12-15 08:06:32.699602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d654562a0fe'
down_revision = '95adbfbc37ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_column('search_count')

    # ### end Alembic commands ###
