"""添加 Snapshot 模型

Revision ID: 6266236a306e
Revises: 1d654562a0fe
Create Date: 2024-12-15 08:23:19.167553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6266236a306e'
down_revision = '1d654562a0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('search_mode', sa.String(length=50), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('sort_field', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.String(length=10), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('results', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot')
    # ### end Alembic commands ###
