"""添加 Snapshot 模型

Revision ID: 9ebe66bd70a4
Revises: 6266236a306e
Create Date: 2024-12-15 08:40:24.595018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ebe66bd70a4'
down_revision = '6266236a306e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_query', sa.String(length=255), nullable=False))
        batch_op.drop_column('sort_order')
        batch_op.drop_column('query')
        batch_op.drop_column('page')
        batch_op.drop_column('file_type')
        batch_op.drop_column('search_mode')
        batch_op.drop_column('sort_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_field', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('search_mode', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('file_type', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('page', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('query', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('sort_order', mysql.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('search_query')

    # ### end Alembic commands ###
